// Demo agent: keeps the hosted dashboard alive with genuine activity.
// Two behaviors, both through the real store contract:
//  1. Traffic — submits realistic MCP tool calls on an interval so the
//     execution list always has fresh rows flowing pending -> ready ->
//     claimed -> completed.
//  2. Chaos — periodically claims an execution with a deliberately short
//     lease, never heartbeats, lets the lease lapse, then attempts a stale
//     completion with the old token. The scheduler reaper and fencing guard
//     do the rest: the dashboard accumulates real lease_expired,
//     stale_rejected, and reclaim arcs without anyone faking rows.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"os"
	"strconv"
	"time"

	"github.com/tyagiquamar/durablemcp/internal/store"
)

func main() {
	dbURL := envOr("DATABASE_URL", "")
	if dbURL == "" {
		log.Fatal("demo-agent: DATABASE_URL is required")
	}
	interval := envIntOr("DEMO_INTERVAL_SECS", 45)
	chaosEvery := envIntOr("DEMO_CHAOS_EVERY", 4)
	namespace := envOr("DEMO_NAMESPACE", "demo")

	ctx := context.Background()
	p, err := store.NewPostgres(ctx, dbURL)
	if err != nil {
		log.Fatalf("demo-agent: connect postgres: %v", err)
	}
	defer p.Close()

	log.Printf("demo-agent started: interval=%ds chaos_every=%d ns=%s", interval, chaosEvery, namespace)

	for i := 0; ; i++ {
		if err := submitToolCall(p, namespace, i); err != nil {
			log.Printf("demo-agent: submit #%d: %v", i, err)
		} else {
			log.Printf("demo-agent: submitted tool call #%d", i)
		}

		if chaosEvery > 0 && i > 0 && i%chaosEvery == 0 {
			if err := runChaosCycle(p); err != nil {
				log.Printf("demo-agent: chaos cycle: %v", err)
			}
		}
		time.Sleep(time.Duration(interval) * time.Second)
	}
}

var demoCalls = []struct {
	tool string
	args json.RawMessage
}{
	{"call_api", json.RawMessage(`{"url":"https://api.github.com/repos/Tyagiquamar/durablemcp"}`)},
	{"call_api", json.RawMessage(`{"url":"https://httpbin.org/get"}`)},
	{"slow_compute", json.RawMessage(`{"seconds":2}`)},
	{"write_file", json.RawMessage(`{"path":"demo/last-run.txt","content":"generated by demo-agent"}`)},
}

func submitToolCall(p *store.Postgres, namespace string, seq int) error {
	call := demoCalls[seq%len(demoCalls)]
	key := fmt.Sprintf("demo-%d-%d", time.Now().Unix(), seq)
	res, err := p.Submit(context.Background(), namespace, call.tool, key, call.args)
	if err != nil {
		return err
	}
	if res.Duplicate {
		log.Printf("demo-agent: duplicate detected for %s (dedupe working)", key)
	}
	return nil
}

// runChaosCycle claims work with a short lease, abandons it, waits out the
// expiry, then tries to complete with the dead token. Everything that happens
// next (lease_expired -> reclaim -> stale_rejected) is produced by the system.
func runChaosCycle(p *store.Postgres) error {
	ctx := context.Background()
	claim, err := p.Claim(ctx, "chaos-agent", 2) // 2s lease, no heartbeats ever
	if errors.Is(err, store.ErrNoWork) {
		log.Printf("demo-agent: chaos found no ready work")
		return nil
	}
	if err != nil {
		return err
	}
	token := claim.FencingToken
	id := claim.ExecutionID
	log.Printf("demo-agent: chaos claimed %s (token %d), abandoning it", id, token)

	time.Sleep(5 * time.Second) // lease lapses; reaper returns it to ready

	err = p.Complete(ctx, id, token, "chaos-agent", json.RawMessage(`{"from":"ghost"}`))
	if errors.Is(err, store.ErrStale) {
		log.Printf("demo-agent: stale completion rejected as expected (%s)", id)
		return nil
	}
	return err
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func envIntOr(key string, fallback int) int {
	if v := os.Getenv(key); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n >= 0 {
			return n
		}
	}
	return fallback
}
